import React from 'react'
import { mount } from 'enzyme'
import toJSON from 'enzyme-to-json'
import wait from 'waait'
import { MockedProvider } from 'react-apollo/test-utils'
import RequestReset, { REQUEST_RESET_MUTATION } from '../components/RequestReset'
